

# Path and variables
vehicle_num: "V12"
VARIABLES : ["DPFDP","DPFINT","ATGMF","ENGINE RPM","THROTTLE","ENGINE LOAD","SPEED","IS"]

# Variable Limits
RPM_RANGE: [1250, 1800]   # RPM limit for diffrential pressure mesurment 
THROTTLE_CUTOFF: 0.5      # Mimimum throttle limit for diffrential pressure mesurment
ENGINE_LOAD_CUTOFF: 90    # Mimimum Engine load limit for diffrential pressure mesurment
ENGINE_IDLE_SWITCH: 0     # Wheel based Vehicle Speed (binary signal same rate sampled as DP)
REGN_INHIBT_SWITCH: 0.5     # Regenration inhibition switch (binary signal but resampling perturb values as its low sampled than DP)



# Thresholds of variables
Thresholds:
  DP_HIGH_MAX: 3.5          # Maximum Threshold for high diffrential pressure
  DP_HIGH_MIN: 3            # Minimum Threshold for high diffrential pressure
  EXT_FLOW_RATE_TH: 325     # Maximum Eaxuast Gas Flow Rate
  DPFINT_TEMP_HIGH_MAX: 550 # Maximum Threshold for high SCR Temprature
  DPFINT_TEMP_HIGH_MIN: 500 # Minimum Threshold for high SCR Temprature
  


